# Generated by Django 5.0 on 2025-11-19 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='卡组名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('daily_new_limit', models.IntegerField(default=20, verbose_name='每日新卡上限')),
                ('daily_review_limit', models.IntegerField(default=200, verbose_name='每日复习上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '卡组',
                'verbose_name_plural': '卡组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='单词/汉字')),
                ('card_type', models.CharField(choices=[('en', '英语'), ('zh', '汉字')], max_length=2, verbose_name='卡片类型')),
                ('state', models.CharField(choices=[('new', '新学'), ('learning', '学习中'), ('review', '复习')], default='new', max_length=10, verbose_name='状态')),
                ('ef', models.FloatField(default=2.5, verbose_name='易忘因子')),
                ('interval', models.IntegerField(default=0, verbose_name='间隔天数')),
                ('difficulty', models.FloatField(default=0, verbose_name='难度')),
                ('stability', models.FloatField(default=0, verbose_name='稳定度')),
                ('lapses', models.IntegerField(default=0, verbose_name='错误次数')),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习时间')),
                ('learning_step', models.IntegerField(default=0, verbose_name='学习步骤')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.deck')),
            ],
            options={
                'verbose_name': '卡片',
                'verbose_name_plural': '卡片',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(choices=[(0, 'Again'), (2, 'Hard'), (4, 'Good'), (5, 'Easy')], verbose_name='评分')),
                ('time_taken', models.IntegerField(verbose_name='耗时(毫秒)')),
                ('before_state', models.CharField(max_length=10, verbose_name='复习前状态')),
                ('before_ef', models.FloatField(verbose_name='复习前EF')),
                ('before_interval', models.IntegerField(verbose_name='复习前间隔')),
                ('before_due_at', models.DateTimeField(verbose_name='复习前到期时间')),
                ('after_state', models.CharField(max_length=10, verbose_name='复习后状态')),
                ('after_ef', models.FloatField(verbose_name='复习后EF')),
                ('after_interval', models.IntegerField(verbose_name='复习后间隔')),
                ('after_due_at', models.DateTimeField(verbose_name='复习后到期时间')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='复习时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '复习记录',
                'verbose_name_plural': '复习记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', '-created_at'], name='cards_deck_user_id_4f4d95_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'due_at'], name='cards_card_user_id_418188_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'deck'], name='cards_card_user_id_51e21a_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['word'], name='cards_card_word_7b43ae_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user', 'state', 'due_at'], name='cards_card_user_id_38c111_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['-lapses'], name='cards_card_lapses_935e54_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['user', '-reviewed_at'], name='cards_revie_user_id_3379a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['card', '-reviewed_at'], name='cards_revie_card_id_3a5b2e_idx'),
        ),
    ]
