# Generated by Django 5.0 on 2025-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='单词')),
                ('phonetic', models.CharField(blank=True, max_length=200, verbose_name='音标')),
                ('definition', models.TextField(blank=True, verbose_name='释义')),
                ('translation', models.TextField(blank=True, verbose_name='中文翻译')),
                ('pos', models.CharField(blank=True, max_length=200, verbose_name='词性')),
                ('collins', models.IntegerField(default=0, verbose_name='柯林斯星级')),
                ('oxford', models.BooleanField(default=False, verbose_name='牛津3000')),
                ('tag', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('bnc', models.IntegerField(blank=True, null=True, verbose_name='BNC词频')),
                ('frq', models.IntegerField(blank=True, null=True, verbose_name='当代语料库词频')),
                ('exchange', models.TextField(blank=True, verbose_name='词形变化')),
                ('detail', models.TextField(blank=True, verbose_name='详细释义')),
                ('audio', models.CharField(blank=True, max_length=200, verbose_name='读音音频URL')),
            ],
            options={
                'verbose_name': 'ECDICT词典',
                'verbose_name_plural': 'ECDICT词典',
                'db_table': 'ecdict',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='ecdict_word_f20953_idx'), models.Index(fields=['collins'], name='ecdict_collins_30e5f9_idx'), models.Index(fields=['oxford'], name='ecdict_oxford_c79312_idx')],
            },
        ),
    ]
