# Generated by Django 5.0 on 2025-11-20 02:25

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_ecdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_at',
            field=models.DateTimeField(default=cards.models.get_default_due_date, verbose_name='下次复习时间'),
        ),
    ]
