# Generated by Django 5.0 on 2025-11-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewlog',
            new_name='cards_revie_user_id_59472e_idx',
            old_name='cards_revie_user_id_review_idx',
        ),
    ]
