# Generated by Django 5.0 on 2025-11-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_cards_revie_user_id_review_idx_cards_revie_user_id_59472e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', help_text='openai, anthropic, local等', max_length=50, verbose_name='AI提供商')),
                ('base_url', models.URLField(default='https://api.openai.com/v1', max_length=500, verbose_name='API Base URL')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', help_text='如: gpt-3.5-turbo, claude-3-sonnet等', max_length=100, verbose_name='模型名称')),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True, verbose_name='加密的API Key')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用AI功能')),
                ('auto_summarize', models.BooleanField(default=False, verbose_name='自动总结')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(default=500, verbose_name='最大Token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
            },
        ),
    ]
