# Generated by Django 5.0 on 2025-11-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='custom_chinese_prompt',
            field=models.TextField(blank=True, help_text='自定义汉字学习卡片生成提示词,留空则使用默认提示词。使用{char}作为汉字占位符,使用{context}作为额外信息占位符', null=True, verbose_name='自定义汉字提示词'),
        ),
    ]
